version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=data_hh
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
      - airflow

  db:
    container_name: pgdb
    image: postgres
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=data_hh
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  airflow:
    container_name: airflow
    image: apache/airflow:2.1.0
    restart: always
    environment:
      - AIRFLOW_DATABASE_URI=postgresql+psycopg2://postgres:postgres@db/data_hh
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    ports:
      - "8080:8080"
    volumes:
      - ./path/airflow.cfg:/usr/local/airflow/airflow.cfg
      - ./dags:/opt/airflow/dags
    depends_on:
      - db


  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: a
    ports:
      - '5050:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  db-data:
  pgadmin-data:
